Activity
sasfmlzr/filemanager pull request #1
Opened 2018-04-11 14:00 UTC by sasfmlzr

2018-04-13 09:38 UTC, 0neel commented
The PR name must briefly describe done changes

2018-04-13 10:15 UTC, 0neel requested changes
Please check the project for similar issues

2018-04-13 10:15 UTC, 0neel commented on app/src/main/AndroidManifest.xml
>  </manifest>
no newline at the end of file

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +        if (countActivity==0){
missing spaces

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +    protected final int READ_EXTERNAL_STORAGE = 0;
constants should be static

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +/** Abstract activity need for easily reading code MainActivity*/
missing empty line before the javadoc

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +/** Abstract activity need for easily reading code MainActivity*/
it's not recommended to make javadoc comments single lined

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +/** Abstract activity need for easily reading code MainActivity*/
No need to mention that the activity is abstract because it's obvious from the code

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +                );
closing brackets must not be on the newline

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +    public void beforeInit(int countActivity){
missing space

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +    private ListView mFileList;
no need to use `m` or any other private fields prefixes

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +/** Abstract activity need for easily reading code MainActivity*/
The comment itself must explain the purpose of the class clear to the reader. For now it's not very obvious what does this class simplifies.

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +public abstract class AbstractActivity extends AppCompatActivity {
I can't understand the purpose of this activity, it handles some different parts of logic not related to each other: permissions checking, adapter setting. Why MainActivity can't be responsible for this?

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +    public void beforeInit(int countActivity){
method names (if it's not a callback method) must start from a verb

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +    public void beforeInit(int countActivity){
this method may be protected or package private because it's not used from other classes

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +                Toast.makeText(this, "Permission is not granted", Toast.LENGTH_SHORT).show();
toast messages should be placed in string resources

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +
unnecessary newline

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +                                           String permissions[], int[] grantResults) {
Incorrect parameters chopping. place parameters either on the single string if they fit 100 characters or in the column on by one.

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +
same

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +                    Toast.makeText(this, "Please allow permissions",Toast.LENGTH_SHORT).show();
same

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +                    mFileList.setAdapter(mFileExploreAdapter);
the logic of adapter setting is not directly connected with the permissions request callback and should be moved into a separate method

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +            case READ_EXTERNAL_STORAGE: {
No need to use `switch-case` if you have a single case. `if` is better for such purposes.

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +    public ListView getmFileList() {
private field prefixes must not be present in getters/setters names

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +    public void setmFileList(ListView mFileList) {
same

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/AbstractActivity.java
> +    public FileExploreAdapter getmFileExploreAdapter() {
same and so on for all other methods in this class

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/MainActivity.java
> +/** View activity*/
missing newline before the javadoc

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/MainActivity.java
> +/** View activity*/
the comment is not really descriptive

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/MainActivity.java
>      private ListView mFileList;
this field duplicates the field from the base class

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/MainActivity.java
> +        if(intent.hasExtra("mCurrentPath")){
missing spaces

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/MainActivity.java
> +        if(intent.hasExtra("mCurrentPath")){
extra names must be class constants

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/MainActivity.java
> +        //Toast.makeText(this, "Main Activity",Toast.LENGTH_SHORT).show();
commented code must not be present in the reviewing code

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/MainActivity.java
>          AdapterView.OnItemClickListener itemListener = new AdapterView.OnItemClickListener() {
better either making activity implementing this interface or creating a nested class implementing it

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/MainActivity.java
> +                if(file.isDirectory()){
missing spaces

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/MainActivity.java
> +                    Intent intent = new Intent(getApplicationContext(), MainActivity.class);
better using Starter pattern to start an activity

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/MainActivity.java
>      public void onClick(View view){
unused code

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/api/other/Param.java
> +    public static int sCountActivity =0;
static fields is not a correct way of passing data between application components. intent extras or listeners must be used instead

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/api/file/FileOperation.java
> +        final boolean showHidden = Settings.showHiddenFiles();
no need to show hidden files, keep the app simple

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/api/adapter/FileExploreAdapter.java
>              dateView =      view.findViewById(R.id.date_view);
unnecessary space

2018-04-13 10:15 UTC, 0neel commented on app/src/main/java/com/sasfmlzr/filemanager/api/other/Permissions.java
> +    /**It's class need for root commands*/
spaces

2018-04-13 13:21 UTC, sasfmlzr commented
fix all

2018-04-26 10:16 UTC, 0neel approved these changes

2018-04-26 10:16 UTC, 0neel commented on app/src/main/AndroidManifest.xml
>  </manifest>
no newline

2018-04-26 10:16 UTC, 0neel commented on app/src/main/AndroidManifest.xml
> -
Those empty lines you've deleted were making manifest more readable. I recommend you to return them back.

2018-04-26 10:16 UTC, 0neel commented on app/src/main/res/xml/filepaths.xml
> +</paths>
no newline

2018-04-26 10:16 UTC, 0neel commented on app/src/main/res/layout/activity_main.xml
>              android:layout_weight="1"
better keeping `layout_weight` close to `layout_width` and `layout_height`

2018-04-26 10:21 UTC, merged